export const USER_LOGIN_REQUEST ="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILLED ="USER_LOGIN_FAILLED"

export const USER_LOGOUT_SUCCESS ="USER_LOGOUT_SUCCESS"


export const USER_UPDATE_REQUEST ="USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCCESS ="USER_UPDATE_SUCCESS"
export const USER_UPDATE_FAILLED ="USER_UPDATE_FAILLED"